[package]
name = "ips"
version = "0.1.0"
edition = "2021"

[dependencies]
clap={ version = "4.5.26", features = ["derive"] }
duct = "0.13.7"
nix = { version = "0.29.0", features = ["net"] }
pnet = "0.35.0"
